spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.100:3306/j213
    username: user01
    password: user01
    hikari:
      initializationFailTimeout: 60000