server:
  port: 8081
spring:
  application:
    name: web
  data:
    mongodb:
      host: 192.168.100.100
      port: 27017
      database: web
logging:
  level:
    root: info
    com.psc.sample: debug
