spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: gateway
          uri: http://localhost:8040
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/my_realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/my_realm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/auth/realms/my_realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          my_client_a:
            provider: keycloak
            client-id: my_client_a
            client-secret: wPqKZOjUi8FHQZYVz8q0cKLHEyjLLF2r
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          my_client_b:
            provider: keycloak
            client-id: my_client_b
            client-secret: NoFQBCVrsfWty5h51gHb0SNOoMGzmTkz
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"



server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
