spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: gateway
          uri: http://127.0.0.1:8040
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://127.0.0.1:8080/auth/realms/my_realm/protocol/openid-connect/token
            authorization-uri: http://127.0.0.1:8080/auth/realms/my_realm/protocol/openid-connect/auth
            userinfo-uri: http://127.0.0.1:8080/auth/realms/my_realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          my_client_a:
            provider: keycloak
            client-id: my_client_a
            client-secret: e685eb5b-82e7-4528-84fc-e97b15b5b07f
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          my_client_b:
            provider: keycloak
            client-id: my_client_b
            client-secret: dd860d16-d498-4743-bf2d-41f253303724
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"



server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE