spring:
  application:
    name: j211
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/j211_schema
    username: user01
    password: user01
    hikari:
      initializationFailTimeout: 60000
logging:
  level:
    root: info
    com.psc.j209: debug
