server:
  port: 443
  ssl:
    enabled: true
    key-store: file:/Users/seungchulpark/github/parkseungchul/j200/j212/src/main/resources/springcloud.pfx
    key-store-password: ccie6198
    key-store-type: PKCS12
    trust-store: file:/Users/seungchulpark/github/parkseungchul/j200/j212/src/main/resources/trust.jks
    trust-store-password: ccie6198
custom:
  area: ssl



