spring:
  application:
    name: biz
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/my_realm
          # 이거 왜 유닉스랑 윈도우랑 다르게 동작하냐...

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: INFO
  org.springframework.web.reactive.function.client: DEBUG
  pl.piomin: DEBUG

server.port: 8040

