server:
  port: 80
logging:
  config: classpath:log4j2.xml

spring:
  h2:
    console:
      enabled: true
      path: /h2
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    username: sa
    password: sa